version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"